import type { Producer, Product, Order, Review } from "./types";

export const MOCK_PRODUCERS: Producer[] = [
  {
    id: "producer-1",
    userId: "user-1",
    name: "Sloeberry Spirits",
    slug: "sloeberry-spirits",
    bio: "Small-batch fruit liqueurs and sloe gin, handcrafted on a Leicestershire farm using traditional infusion methods and the finest handpicked fruits.",
    story: "We started Sloeberry Spirits because we wanted to do something with the extraordinary bounty growing wild around our farm on the Rutland-Leicestershire border — hedgerows bursting with sloe berries, damsons, and raspberries that deserved more than just being left to the birds. Using traditional infusion techniques passed down through generations, we began steeping handpicked fruits with quality base spirits, letting time and patience do the work to create liqueurs of genuine depth and character. Our award-winning Sloe Gin was just the beginning — customer curiosity and a spirit of experimentation led us to a whole dessert range too, from velvety Salted Caramel to rich Chocolate Orange. Every bottle we make is a small act of love for this corner of England, and we hope that comes through in every sip.",
    location: "Melton Mowbray, Leicestershire",
    address: {
      line1: "",
      city: "Melton Mowbray",
      county: "Leicestershire",
      postcode: "LE14",
      country: "GB",
    },
    categories: ["Liqueurs","Sloe Gin","Fruit Spirits","Gifts"],
    images: {
      banner: "/images/hero.jpg",
      logo: "/images/hero.jpg",
    },
    status: "approved",
    commissionRate: 0,
    fulfilmentOptions: ["ship", "collect"],
    socialLinks: {
      instagram: "@sloeberryspirits",
      facebook: "sloeberryspirits",
    },
    rating: 4.8,
    reviewCount: 124,
    createdAt: new Date("2018-01-01"),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    producerId: "producer-1",
    producerName: "Sloeberry Spirits",
    producerSlug: "sloeberry-spirits",
    name: "Award-Winning Sloe Gin",
    description: "The one that started it all. Plump sloe berries, handpicked from the hedgerows surrounding our Leicestershire farm, are steeped slowly in fine gin until they surrender every drop of their deep, ruby-red intensity. The result is a liqueur of real elegance — tart wild berry on the nose, warming juniper at the heart, and a long, velvety finish that lingers beautifully.",
    slug: "award-winning-sloe-gin",
    category: "Fruit Liqueurs",
    price: 2850,
    unit: "35cl bottle (20% ABV)",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: ["vegan"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-2",
    producerId: "producer-1",
    producerName: "Sloeberry Spirits",
    producerSlug: "sloeberry-spirits",
    name: "Gin & Raspberry Liqueur",
    description: "Bright, blushing, and bursting with summer fruit, this raspberry-infused gin liqueur captures the very essence of a sun-warmed English hedgerow. Fresh raspberries are slow-infused with a crisp, quality gin base, creating a liqueur that's vibrantly fruity yet beautifully balanced — perfect over ice, in a spritz, or drizzled over vanilla ice cream.",
    slug: "gin-raspberry-liqueur",
    category: "Fruit Liqueurs",
    price: 2850,
    unit: "35cl bottle (20% ABV)",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: ["vegan"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-3",
    producerId: "producer-1",
    producerName: "Sloeberry Spirits",
    producerSlug: "sloeberry-spirits",
    name: "Whisky & Wild Damson Liqueur",
    description: "Deep, brooding, and wonderfully complex — this is a liqueur for those who like their drinks to have a story. Wild damsons, foraged from the farm's ancient hedgerows, are infused with a smooth Scotch whisky base, lending notes of dark plum, subtle smokiness, and a warm, honeyed finish that wraps around you like a winter evening by the fire.",
    slug: "whisky-wild-damson-liqueur",
    category: "Fruit Liqueurs",
    price: 2850,
    unit: "35cl bottle (20% ABV)",
    stock: 50,
    images: ["/images/whisky-wild-damson-liqueur.jpg"],
    dietary: ["vegan"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-4",
    producerId: "producer-1",
    producerName: "Sloeberry Spirits",
    producerSlug: "sloeberry-spirits",
    name: "Salted Caramel Vodka Liqueur",
    description: "Born from a customer request we couldn't resist, our Salted Caramel Vodka surprised even us when we first tasted it. Buttery, golden caramel is balanced with a whisper of sea salt and a smooth vodka base, creating something wonderfully indulgent — rich enough to sip on its own, but equally brilliant poured into a milkshake or over a scoop of vanilla ice cream.",
    slug: "salted-caramel-vodka-liqueur",
    category: "Dessert Liqueurs",
    price: 2850,
    unit: "35cl bottle (17% ABV)",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: ["vegetarian"],
    allergens: ["dairy"],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-5",
    producerId: "producer-1",
    producerName: "Sloeberry Spirits",
    producerSlug: "sloeberry-spirits",
    name: "Chocolate Orange Vodka Liqueur",
    description: "Every sip of this deeply satisfying liqueur tastes like unwrapping something special. Rich dark chocolate and zesty Valencian orange are blended with a smooth vodka base into something that's equal parts pudding and indulgence — serve chilled after dinner, splash into hot chocolate, or gift to someone who deserves a treat.",
    slug: "chocolate-orange-vodka-liqueur",
    category: "Dessert Liqueurs",
    price: 2850,
    unit: "35cl bottle (17% ABV)",
    stock: 50,
    images: ["/images/chocolate-orange-vodka-liqueur.jpg"],
    dietary: ["vegetarian"],
    allergens: ["dairy"],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-6",
    producerId: "producer-1",
    producerName: "Sloeberry Spirits",
    producerSlug: "sloeberry-spirits",
    name: "Coffee Vodka Liqueur",
    description: "Smooth, dark, and gloriously aromatic — our Coffee Vodka Liqueur is made with real roasted coffee steeped in a quality vodka base, delivering a cup-like intensity without any of the bitterness. The perfect after-dinner sipper, a brilliant espresso martini ingredient, or a morning-inspired treat for those who like their spirits to carry a little caffeine swagger.",
    slug: "coffee-vodka-liqueur",
    category: "Dessert Liqueurs",
    price: 2850,
    unit: "35cl bottle (17% ABV)",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: ["vegan"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-7",
    producerId: "producer-1",
    producerName: "Sloeberry Spirits",
    producerSlug: "sloeberry-spirits",
    name: "Fruit Liqueur Tasting Trio",
    description: "The perfect introduction to the Sloeberry Spirits range — or a beautifully considered gift for someone with a curious palate. This curated trio brings together three of our most-loved fruit liqueurs in a presentation set: our award-winning Sloe Gin, the vivid Gin & Raspberry, and the brooding Whisky & Wild Damson. Nestled in a gift box with a tasting note card, it arrives ready to delight.",
    slug: "fruit-liqueur-tasting-trio",
    category: "Gifts",
    price: 6500,
    unit: "Gift set — three 10cl bottles",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: ["vegan"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-8",
    producerId: "producer-1",
    producerName: "Sloeberry Spirits",
    producerSlug: "sloeberry-spirits",
    name: "Dessert Liqueur Duo Gift Box",
    description: "Two of our most indulgent creations, presented together in a premium gift box for the person in your life who has impeccable taste in after-dinner treats. Pair our velvet-smooth Salted Caramel Vodka with the dark, citrus-kissed Chocolate Orange Vodka for a gift that genuinely surprises and delights — elegant enough for a birthday, but honestly perfect for any occasion.",
    slug: "dessert-liqueur-duo-gift-box",
    category: "Gifts",
    price: 5200,
    unit: "Gift set — two 35cl bottles",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: ["vegetarian"],
    allergens: ["dairy"],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    orderId: "order-1",
    consumerId: "consumer-1",
    consumerName: "Sarah M.",
    producerId: "producer-1",
    rating: 5,
    comment: "Absolutely outstanding. Award-Winning Sloe Gin was everything the description promised and more. Beautifully packaged, arrived perfectly fresh. Already placed my second order.",
    createdAt: new Date("2024-04-07"),
  },
  {
    id: "rev-2",
    orderId: "order-2",
    consumerId: "consumer-2",
    consumerName: "James T.",
    producerId: "producer-1",
    rating: 5,
    comment: "Sent a selection as a gift and got a phone call from my parents saying it was the best thing they'd ever received. Quality you simply cannot find in a supermarket. Will be ordering monthly.",
    createdAt: new Date("2024-04-21"),
  },
  {
    id: "rev-3",
    orderId: "order-3",
    consumerId: "consumer-3",
    consumerName: "Rachel H.",
    producerId: "producer-1",
    rating: 5,
    comment: "I've been ordering from Sloeberry Spirits for six months now and the quality has never dipped once. Proper craft food made by people who genuinely care. Nothing else comes close.",
    createdAt: new Date("2024-05-04"),
  },
];

export const MOCK_ORDERS: Order[] = [];
