import type { Producer, Product, Order, Review } from "./types";

export const MOCK_PRODUCERS: Producer[] = [
  {
    id: "producer-1",
    userId: "user-1",
    name: "Sloeberry Spirits",
    slug: "sloeberry-spirits",
    bio: "Family-run farm distillery on the Rutland-Leicestershire border, crafting award-winning small-batch fruit and dessert liqueurs the traditional way.",
    story: "We started Sloeberry Spirits because we wanted to do something meaningful with the extraordinary fruit that grows around our farm — the hedgerows here are bursting with sloes, damsons and raspberries, and it felt like a shame not to celebrate them. Using traditional slow-infusion methods passed down through generations, we began crafting liqueurs that truly taste of this corner of England. What started as a sloe gin made for friends has grown into a whole range of fruit and dessert liqueurs, each one made with the same care and obsession for flavour that we put into that very first batch. Every bottle we sell still goes out with the same pride — this is our farm, our fruit, and our family in every drop.",
    location: "Melton Mowbray, Leicestershire",
    address: {
      line1: "",
      city: "Melton Mowbray",
      county: "Leicestershire",
      postcode: "LE14",
      country: "GB",
    },
    categories: ["liqueurs","gin"],
    images: {
      banner: "/images/hero.jpg",
      logo: "/images/hero.jpg",
    },
    status: "approved",
    commissionRate: 0,
    fulfilmentOptions: ["ship", "collect"],
    socialLinks: {
      instagram: "@sloeberryspirits",
      facebook: "sloeberryspirits",
    },
    rating: 4.8,
    reviewCount: 124,
    createdAt: new Date("2015-01-01"),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    producerId: "producer-1",
    producerName: "Sloeberry Spirits",
    producerSlug: "sloeberry-spirits",
    name: "Award-Winning Sloe Gin Liqueur",
    description: "The one that started it all. Hand-foraged sloe berries from the hedgerows surrounding our Leicestershire farm are slow-infused with premium gin over several months, yielding a deep ruby liqueur with a beautifully balanced bittersweet character — rich dark fruit up front, a warming almond-like finish, and just the right amount of sharpness to keep things interesting. Sip neat, pour over ice, or stir into a Sloe Gin Fizz.",
    slug: "award-winning-sloe-gin-liqueur",
    category: "liqueurs",
    price: 2499,
    unit: "35cl bottle (approx. 12 servings)",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: ["vegan"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-2",
    producerId: "producer-1",
    producerName: "Sloeberry Spirits",
    producerSlug: "sloeberry-spirits",
    name: "Gin & Raspberry Liqueur",
    description: "Vibrant, jewel-bright and utterly moreish — this liqueur captures the essence of sun-ripened British raspberries in a way that no cordial or mixer ever could. Premium gin provides a crisp, botanical backbone while the fruit brings an irresistible natural sweetness with a zingy, fresh-berry finish. Wonderful over ice, splashed into prosecco, or drizzled over vanilla ice cream for a truly grown-up dessert.",
    slug: "gin-raspberry-liqueur",
    category: "liqueurs",
    price: 2499,
    unit: "35cl bottle (approx. 12 servings)",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: ["vegan"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-3",
    producerId: "producer-1",
    producerName: "Sloeberry Spirits",
    producerSlug: "sloeberry-spirits",
    name: "Whisky & Wild Damson Liqueur",
    description: "A brooding, complex liqueur that pairs the smoky warmth of quality Scotch whisky with the tartly sweet depth of wild-foraged damsons. The result is something deeply satisfying — layers of plum, dried fruit and gentle spice, with the whisky's oakiness providing a long, lingering finish. This one is best savoured slowly by a fire, ideally with good company and nowhere else to be.",
    slug: "whisky-wild-damson-liqueur",
    category: "liqueurs",
    price: 2699,
    unit: "35cl bottle (approx. 12 servings)",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: ["vegan"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-4",
    producerId: "producer-1",
    producerName: "Sloeberry Spirits",
    producerSlug: "sloeberry-spirits",
    name: "Salted Caramel Vodka Liqueur",
    description: "Born out of pure curiosity after countless customers asked for it at markets, our Salted Caramel Vodka turned out to be a revelation. Smooth premium vodka is blended with real caramel and a precise pinch of sea salt to create something indulgently silky — sweet without being cloying, with a gorgeous warm, buttery finish. Pour it over ice cream, mix it into a White Russian, or simply sip it straight as a dessert in a glass.",
    slug: "salted-caramel-vodka-liqueur",
    category: "liqueurs",
    price: 2499,
    unit: "35cl bottle (approx. 12 servings)",
    stock: 50,
    images: ["/images/salted-caramel-vodka-liqueur.jpg"],
    dietary: ["vegetarian"],
    allergens: ["dairy"],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-5",
    producerId: "producer-1",
    producerName: "Sloeberry Spirits",
    producerSlug: "sloeberry-spirits",
    name: "Chocolate Orange Vodka Liqueur",
    description: "Rich, velvety and unashamedly indulgent, this dessert liqueur brings together the classic pairing of dark chocolate and zesty Valencia orange in a smooth, sippable form. Real cocoa and natural orange oil give it an authenticity that synthetic flavourings simply can't match — you get a genuine bittersweet chocolate hit followed by a bright, citrusy lift. Serve chilled after dinner, mix with cream for the ultimate cocktail, or gift to someone you want to seriously impress.",
    slug: "chocolate-orange-vodka-liqueur",
    category: "liqueurs",
    price: 2499,
    unit: "35cl bottle (approx. 12 servings)",
    stock: 50,
    images: ["/images/chocolate-orange-vodka-liqueur.jpg"],
    dietary: ["vegetarian"],
    allergens: ["dairy"],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-6",
    producerId: "producer-1",
    producerName: "Sloeberry Spirits",
    producerSlug: "sloeberry-spirits",
    name: "Coffee Vodka Liqueur",
    description: "For coffee lovers who also love a proper drink, this is your perfect pour. We've taken premium vodka and infused it with freshly roasted coffee to create a liqueur that's bold, aromatic and genuinely coffee-forward — none of the artificial sweetness that plagues lesser versions. It makes a sensational Espresso Martini, transforms a scoop of vanilla ice cream into something extraordinary, or simply hits the spot served over ice when you need a lift that's just a little bit special.",
    slug: "coffee-vodka-liqueur",
    category: "liqueurs",
    price: 2499,
    unit: "35cl bottle (approx. 12 servings)",
    stock: 50,
    images: ["/images/coffee-vodka-liqueur.jpg"],
    dietary: ["vegan"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-7",
    producerId: "producer-1",
    producerName: "Sloeberry Spirits",
    producerSlug: "sloeberry-spirits",
    name: "Melton Mowbray Liqueur Gift Set",
    description: "Can't choose just one? Neither can we — which is why we've put together this beautifully presented gift set showcasing three of our most-loved Sloeberry Spirits liqueurs. Nestled in a branded gift box, you'll receive three 35cl bottles from our fruit and dessert ranges, making it the ideal gift for birthdays, Christmas, anniversaries or simply as a treat for someone who appreciates the finer things in life. A true taste of the English countryside, ready to gift.",
    slug: "melton-mowbray-liqueur-gift-set",
    category: "liqueurs",
    price: 6999,
    unit: "Gift set — 3 x 35cl bottles",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: ["vegan"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "prod-8",
    producerId: "producer-1",
    producerName: "Sloeberry Spirits",
    producerSlug: "sloeberry-spirits",
    name: "Miniature Taster Collection",
    description: "New to Sloeberry Spirits or simply want to explore the full range before committing to a full bottle? Our miniature taster collection brings together five of our signature liqueurs in 5cl tasting bottles — from the hedgerow depth of Sloe Gin to the dessert decadence of Salted Caramel — all presented in a neat gift box that's perfect for curious drinkers or as a stocking filler. It's the most delicious way to discover your favourite.",
    slug: "miniature-taster-collection",
    category: "liqueurs",
    price: 2499,
    unit: "Gift set — 5 x 5cl miniatures",
    stock: 50,
    images: ["/images/hero.jpg"],
    dietary: ["vegan"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: false,
    createdAt: new Date("2024-01-01"),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    orderId: "order-1",
    consumerId: "consumer-1",
    consumerName: "Sarah M.",
    producerId: "producer-1",
    rating: 5,
    comment: "Absolutely outstanding. Award-Winning Sloe Gin Liqueur was everything the description promised and more. Beautifully packaged, arrived perfectly fresh. Already placed my second order.",
    createdAt: new Date("2024-04-07"),
  },
  {
    id: "rev-2",
    orderId: "order-2",
    consumerId: "consumer-2",
    consumerName: "James T.",
    producerId: "producer-1",
    rating: 5,
    comment: "Sent a selection as a gift and got a phone call from my parents saying it was the best thing they'd ever received. Quality you simply cannot find in a supermarket. Will be ordering monthly.",
    createdAt: new Date("2024-04-21"),
  },
  {
    id: "rev-3",
    orderId: "order-3",
    consumerId: "consumer-3",
    consumerName: "Rachel H.",
    producerId: "producer-1",
    rating: 5,
    comment: "I've been ordering from Sloeberry Spirits for six months now and the quality has never dipped once. Proper craft food made by people who genuinely care. Nothing else comes close.",
    createdAt: new Date("2024-05-04"),
  },
];

export const MOCK_ORDERS: Order[] = [];
