import type { Producer, Product, Order, Review } from "./types";

export const MOCK_PRODUCERS: Producer[] = [
  {
    id: "producer-1",
    userId: "user-1",
    name: "Orchard & Hop",
    slug: "orchard-and-hop",
    bio: "Small-batch cider, perry, and craft ales from a working farm and brewery in Ledbury, Herefordshire. We press apples from our own century-old orchards and brew in a converted stone barn — slowly, patiently, and without shortcuts.",
    story:
      "My grandfather planted most of our orchards in the 1940s using traditional Herefordshire bittersweet and bittersharp varieties that commercial growers had largely abandoned. When I took over the farm in 2011, I found 40 acres of ancient apple and pear trees producing fruit that tasted extraordinary — complex, tannic, deeply flavoured — and no-one was pressing them. We built the cidery first, in an old cattle barn, using a Victorian rack-and-cloth press we found on the farm. The fermentation is slow — sometimes eight months in old oak vats — and completely natural using wild yeast from the orchard skins. A few years later we added the brewery, using hops we grow ourselves on a south-facing wall alongside the barn. All our ciders are unpasteurised and unfiltered. The beers are unfined and naturally conditioned. These are living drinks that change with the seasons, and we wouldn't have it any other way.",
    location: "Ledbury, Herefordshire",
    address: {
      line1: "The Old Cattle Barn, Orchard Lane",
      city: "Ledbury",
      county: "Herefordshire",
      postcode: "HR8 2AY",
      country: "GB",
    },
    categories: ["cider", "beer"],
    images: {
      banner:
        "https://images.unsplash.com/photo-1569937756344-f9a024f80046?w=1400&q=80",
      logo: "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=200&q=80",
    },
    status: "approved",
    commissionRate: 0,
    fulfilmentOptions: ["ship", "collect"],
    socialLinks: {
      instagram: "@orchardandhop",
      facebook: "OrchardAndHop",
    },
    rating: 4.8,
    reviewCount: 493,
    createdAt: new Date("2011-09-01"),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    producerId: "producer-1",
    producerName: "Orchard & Hop",
    producerSlug: "orchard-and-hop",
    name: "Orchard Dry Cider (6 × 500ml)",
    description:
      "Our flagship dry cider — pressed from a blend of Dabinett, Yarlington Mill, and Brown Snout apples from our century-old orchards. Fermented over eight months in old oak vats using wild yeast. Completely dry, tannin-rich, and complex. The kind of cider that makes wine drinkers stop and pay attention.",
    slug: "orchard-dry-cider-6-pack",
    category: "cider",
    price: 1400,
    unit: "6 × 500ml bottles",
    stock: 60,
    images: [
      "https://images.unsplash.com/photo-1569937756344-f9a024f80046?w=800&q=80",
    ],
    dietary: ["vegan", "gluten-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "prod-2",
    producerId: "producer-1",
    producerName: "Orchard & Hop",
    producerSlug: "orchard-and-hop",
    name: "Medium Sweet Farmhouse Cider (6 × 500ml)",
    description:
      "A gently sweet cider with the same orchard complexity as our dry, but blended at the press to retain a touch of natural fruit sweetness. Approachable for all palates, with a clean apple finish and none of the cloying sweetness of commercial brands.",
    slug: "medium-sweet-farmhouse-cider-6-pack",
    category: "cider",
    price: 1350,
    unit: "6 × 500ml bottles",
    stock: 55,
    images: [
      "https://images.unsplash.com/photo-1569937756344-f9a024f80046?w=800&q=80",
    ],
    dietary: ["vegan", "gluten-free"],
    allergens: [],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "prod-3",
    producerId: "producer-1",
    producerName: "Orchard & Hop",
    producerSlug: "orchard-and-hop",
    name: "Herefordshire Perry (4 × 500ml)",
    description:
      "True perry — not pear cider — made from our own Thorn and Moorcroft pear trees. Delicate, floral, and ethereally light compared to apple cider. Naturally still, lightly tannic, and completely unlike anything sold commercially. We make fewer than 2,000 bottles a year.",
    slug: "herefordshire-perry-4-pack",
    category: "cider",
    price: 1400,
    unit: "4 × 500ml bottles",
    stock: 25,
    images: [
      "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=800&q=80",
    ],
    dietary: ["vegan", "gluten-free"],
    allergens: [],
    seasonal: true,
    available: true,
    featured: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "prod-4",
    producerId: "producer-1",
    producerName: "Orchard & Hop",
    producerSlug: "orchard-and-hop",
    name: "Barn Pale Ale (4 × 440ml)",
    description:
      "Our session pale ale — dry-hopped with home-grown Cascade and Centennial hops for a fresh, citrusy aroma and a crisp, bitter finish. 4.2% ABV. Naturally carbonated and unfined — there may be a light haze, which is what honest beer looks like.",
    slug: "barn-pale-ale-4-pack",
    category: "beer",
    price: 1050,
    unit: "4 × 440ml cans",
    stock: 80,
    images: [
      "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=800&q=80",
    ],
    dietary: ["vegan"],
    allergens: ["gluten"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "prod-5",
    producerId: "producer-1",
    producerName: "Orchard & Hop",
    producerSlug: "orchard-and-hop",
    name: "Cider & Beer Tasting Case (12 mixed)",
    description:
      "The best introduction to what we make — four bottles of our Orchard Dry Cider, four of our Medium Sweet, two of our Perry, and two cans of Barn Pale Ale. A tasting notes card included. The perfect starter case, and a popular gift.",
    slug: "cider-beer-tasting-case",
    category: "cider",
    price: 2800,
    unit: "12 mixed bottles & cans",
    stock: 30,
    images: [
      "https://images.unsplash.com/photo-1569937756344-f9a024f80046?w=800&q=80",
    ],
    dietary: ["vegan"],
    allergens: ["gluten"],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "prod-6",
    producerId: "producer-1",
    producerName: "Orchard & Hop",
    producerSlug: "orchard-and-hop",
    name: "Elderflower Cider (4 × 330ml)",
    description:
      "Our dry cider co-fermented with fresh elderflowers picked from the hedgerows around our orchards in June. Delicate, floral, and lightly sparkling. Only available from July to October each year — when the elderflowers run out, this year's batch is gone.",
    slug: "elderflower-cider-4-pack",
    category: "cider",
    price: 1250,
    unit: "4 × 330ml bottles",
    stock: 20,
    images: [
      "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=800&q=80",
    ],
    dietary: ["vegan", "gluten-free"],
    allergens: [],
    seasonal: true,
    available: true,
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "prod-7",
    producerId: "producer-1",
    producerName: "Orchard & Hop",
    producerSlug: "orchard-and-hop",
    name: "Dark Mild Ale (4 × 440ml)",
    description:
      "A low-ABV (3.6%) dark mild brewed with chocolate malt and roasted barley for a gentle bitterness and a deep, malty body. Sessionable, comforting, and entirely out of fashion — which is exactly why we brew it. Outstanding with mature cheddar and a open fire.",
    slug: "dark-mild-ale-4-pack",
    category: "beer",
    price: 950,
    unit: "4 × 440ml cans",
    stock: 50,
    images: [
      "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=800&q=80",
    ],
    dietary: ["vegan"],
    allergens: ["gluten"],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "prod-8",
    producerId: "producer-1",
    producerName: "Orchard & Hop",
    producerSlug: "orchard-and-hop",
    name: "Sparkling Apple Juice (6 × 330ml)",
    description:
      "Pressed from the same orchard apples as our cider, lightly carbonated and unfiltered. No added sugar, no concentrate, no preservatives. For those who want the orchard experience without the alcohol. Also excellent mixed with our dry cider at a 50/50 ratio.",
    slug: "sparkling-apple-juice-6-pack",
    category: "cider",
    price: 900,
    unit: "6 × 330ml bottles",
    stock: 45,
    images: [
      "https://images.unsplash.com/photo-1569937756344-f9a024f80046?w=800&q=80",
    ],
    dietary: ["vegan", "gluten-free"],
    allergens: [],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-01-25"),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    orderId: "order-1",
    consumerId: "consumer-1",
    consumerName: "Ben K.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "The dry cider is extraordinary — genuinely one of the best drinks I've ever had. The tannin structure is like a Burgundy, not a fizzy soft drink. I've been ordering a case a month ever since I discovered it and I can't imagine going back.",
    createdAt: new Date("2024-04-06"),
  },
  {
    id: "rev-2",
    orderId: "order-2",
    consumerId: "consumer-2",
    consumerName: "Rachel S.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "The perry converted me completely. I'd never had real perry before — just the supermarket versions — and this is an entirely different drink. Floral, delicate, and complex. The tasting case was a revelation.",
    createdAt: new Date("2024-04-20"),
  },
  {
    id: "rev-3",
    orderId: "order-3",
    consumerId: "consumer-3",
    consumerName: "Dan T.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "Bought the tasting case as a birthday gift for my father who's been drinking the same lager for 40 years. He's now on his third case of the dry cider. Mission accomplished. Brilliant packaging and fast delivery too.",
    createdAt: new Date("2024-05-03"),
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "order-demo-1",
    consumerId: "consumer-1",
    consumerName: "Demo Customer",
    items: [
      {
        productId: "prod-1",
        productName: "Orchard Dry Cider (6 × 500ml)",
        producerId: "producer-1",
        producerName: "Orchard & Hop",
        price: 1400,
        quantity: 2,
        unit: "6 × 500ml bottles",
        imageUrl:
          "https://images.unsplash.com/photo-1569937756344-f9a024f80046?w=400&q=80",
      },
      {
        productId: "prod-3",
        productName: "Herefordshire Perry (4 × 500ml)",
        producerId: "producer-1",
        producerName: "Orchard & Hop",
        price: 1400,
        quantity: 1,
        unit: "4 × 500ml bottles",
        imageUrl:
          "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?w=400&q=80",
      },
    ],
    producerIds: ["producer-1"],
    status: "delivered",
    fulfilmentMethod: "delivery",
    deliveryAddress: {
      line1: "12 Church Lane",
      city: "Ledbury",
      postcode: "HR8 1DW",
      country: "GB",
    },
    subtotal: 4200,
    commission: 0,
    deliveryFee: 395,
    total: 4595,
    stripePaymentIntentId: "pi_demo_cider_001",
    createdAt: new Date("2024-04-09"),
    updatedAt: new Date("2024-04-10"),
  },
];
